// <auto-generated />
using DragonCards.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DragonCards.Persistence.Migrations
{
    [DbContext(typeof(DragonCardsDbContext))]
    [Migration("20260712050333_AddProfileSeedRuns")]
    partial class AddProfileSeedRuns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DragonCards.Persistence.AppSettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.CardCopyEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId", "CardId");

                    b.ToTable("CardCopies", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.DeckCardEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("CardId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Copies")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId", "DeckId", "CardId");

                    b.ToTable("DeckCards", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.DeckEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeckId")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModeId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId", "DeckId");

                    b.HasIndex("ProfileId", "Name");

                    b.ToTable("Decks", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.PackInventoryEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("PackId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId", "PackId");

                    b.ToTable("PackInventory", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.ProfileEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("ActiveDeckId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultRulesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastPlayedUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedStarterDeckId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.ProfileEventEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "OccurredUnixMilliseconds");

                    b.ToTable("ProfileEvents", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.ProfileSeedRunEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlgorithmVersion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<long>("AppliedUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scenario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<long>("Seed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "AppliedUnixMilliseconds");

                    b.ToTable("ProfileSeedRuns", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.QuestEntryEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId", "QuestId");

                    b.ToTable("QuestEntries", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.QuestStateEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("DailyPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeeklyPeriod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId");

                    b.ToTable("QuestStates", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.StarterDeckOwnershipEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("StarterDeckId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.HasKey("ProfileId", "StarterDeckId");

                    b.ToTable("StarterDeckOwnership", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.TutorialCompletionEntity", b =>
                {
                    b.Property<string>("ProfileId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TutorialId")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<long>("CompletedUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProfileId", "TutorialId");

                    b.ToTable("TutorialCompletions", (string)null);
                });

            modelBuilder.Entity("DragonCards.Persistence.CardCopyEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.DeckCardEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.DeckEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId", "DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.DeckEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.PackInventoryEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.ProfileEventEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.ProfileSeedRunEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.QuestEntryEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.QuestStateEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.StarterDeckOwnershipEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DragonCards.Persistence.TutorialCompletionEntity", b =>
                {
                    b.HasOne("DragonCards.Persistence.ProfileEntity", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
